### ISSUE TITLE
Issue with oauth_signature when using RestSharp 

### ISSUE THREAD

**Issue by RamuBalachandran** [simplificator/simplificator-withings#20]
Hi,
    I successfully used rest sharp for getting the final oauth_token and oauth_token_secret, but when I try get the protected resource , its always returning  342  "The signature (using Oauth) is invalid.". I am using C# .Any help on this much appreciated .

Thank You

**Comment by pascalbetz** [comment]
so you are not using whitings-gem but trying to access the whitings API through C#?

• • •

Pascal Betz

Simplificator AG ⋅ Pfingstweidstrasse 6 ⋅ CH-8005 Zürich
Main +41 44 500 47 50 ⋅ Direct +41 44 500 47 53
pascal.betz@simplificator.com ⋅ www.simplificator.com
vCard: www.simplificator.com/pascal-betz.vcf

Am Donnerstag, 6. November 2014 um 10:17 schrieb RamuBalachandran:

**Comment by RamuBalachandran** [comment]
i am trying to develop a .net client for consuming withings Apis, Presently I am using RestSharp Library

**Comment by pascalbetz** [comment]
According to the doc: 342 : The signature (using Oauth) is invalid

So you might be calculating the secret the wrong way? Check the code for connection.rb to find a sample how we do it.

I'll close this issue as it is not an issue with the gem. Contact me (see message above for email) directly if you need to.
