### ISSUE TITLE
Withings client?

### ISSUE THREAD

**Issue by yashwinkumar** [simplificator/simplificator-withings#5]
I already have a model with name User.
How will i get the withings client?

I used oauth authentication
and got userid, oauth_token, but i dint received any oauth_secret received instead oauth_verifier.

Ultimately i need "measure?action=getmeas" of the user.

**Comment by pascalbetz** [comment]
It is scoped to Withings. Just do not 

```
include Withings
User.authenticate
```

But

```
Withings::User
```

I close this issue, please re-open if required.
Pascal

**Comment by yashwinkumar** [comment]
Yes, I used Withings::User.authenticate()
According to your documentation and method, i need to pass oauth_token_secret, but i am getting userid, oauth_token and oauth_verifier from the api not oauth_token_secret.

Withings.consumer_key = WITHINGS_KEY
Withings.consumer_secret = WITHINGS_SECRET
Withings::User.authenticate(userid, oauth_token, ' ' )

I am getting error

Withings::ApiError: Failed to verify signature - Status code: 342

```
from /home/startup/.rvm/gems/ruby-1.9.3-p385/gems/simplificator-withings-0.6.6/lib/withings/connection.rb:87:in `verify_response!'
from /home/startup/.rvm/gems/ruby-1.9.3-p385/gems/simplificator-withings-0.6.6/lib/withings/connection.rb:22:in `get_request'
from /home/startup/.rvm/gems/ruby-1.9.3-p385/gems/simplificator-withings-0.6.6/lib/withings/user.rb:5:in `authenticate'
from (irb):5
from /home/startup/.rvm/gems/ruby-1.9.3-p385/gems/railties-3.2.8/lib/rails/commands/console.rb:47:in `start'
from /home/startup/.rvm/gems/ruby-1.9.3-p385/gems/railties-3.2.8/lib/rails/commands/console.rb:8:in `start'
from /home/startup/.rvm/gems/ruby-1.9.3-p385/gems/railties-3.2.8/lib/rails/commands.rb:41:in `<top (required)>'
from script/rails:6:in `require'
from script/rails:6:in `<main>'
```
