### ISSUE TITLE
Withings client?

### ISSUE THREAD

**Issue by yashwinkumar** [simplificator/simplificator-withings#6]
Yes, I used Withings::User.authenticate()
According to your documentation and method, i need to pass oauth_token_secret, but i am getting userid, oauth_token and oauth_verifier from the api not oauth_token_secret.

Withings.consumer_key = WITHINGS_KEY
Withings.consumer_secret = WITHINGS_SECRET
Withings::User.authenticate(userid, oauth_token, ' ' )

I am getting error

Withings::ApiError: Failed to verify signature - Status code: 342

```
from /home/startup/.rvm/gems/ruby-1.9.3-p385/gems/simplificator-withings-0.6.6/lib/withings/connection.rb:87:in `verify_response!'
from /home/startup/.rvm/gems/ruby-1.9.3-p385/gems/simplificator-withings-0.6.6/lib/withings/connection.rb:22:in `get_request'
from /home/startup/.rvm/gems/ruby-1.9.3-p385/gems/simplificator-withings-0.6.6/lib/withings/user.rb:5:in `authenticate'
from (irb):5
from /home/startup/.rvm/gems/ruby-1.9.3-p385/gems/railties-3.2.8/lib/rails/commands/console.rb:47:in `start'
from /home/startup/.rvm/gems/ruby-1.9.3-p385/gems/railties-3.2.8/lib/rails/commands/console.rb:8:in `start'
from /home/startup/.rvm/gems/ruby-1.9.3-p385/gems/railties-3.2.8/lib/rails/commands.rb:41:in `<top (required)>'
from script/rails:6:in `require'
from script/rails:6:in `<main>'
```

**Comment by yashwinkumar** [comment]
Actually mistake is mine,
I was using requestToken's token for WIthings::User.authenticate ()

After see withings-api gem example am able to get token and secret

https://github.com/webmonarch/withings-api/blob/master/examples/create_access_token.rb

And passing userid.to_i , token and secret solved my problem

**Comment by pascalbetz** [comment]
Glad to hear it works for you.
